#!/bin/bash
#
# Copyright (C) 2014 eNovance SAS <licensing@enovance.com>
#
# Author: Frederic Lepied <frederic.lepied@enovance.com>
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

src="$1"
dir="$2"
version="$3"
ROLE=install-server

ORIG=$(cd $(dirname $0); pwd)

. ${ORIG}/functions

PATH=/sbin:/bin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
export PATH

if [ -z "$OS_VERS" ]; then
    echo "OS_VERS is not set, Icehouse will be built by default"
    OS_VERS=icehouse
fi

update_repositories $dir

###########
# eDeploy #
###########

$ORIG/deploy.install $dir $dir $version
install_packages_disabled $dir dnsmasq


#################
# Puppet master #
#################

$SRC/puppet-master.install $dir $dir $version

##############
# Serverspec #
##############

case "$OS" in
    "RedHatEnterpriseServer")
        case "$CODENAME_MAJOR" in
            6)
                RAKE=rake
                ;;
            7)
                RAKE=rubygem-rake
                ;;
        esac
        add_epel_repository $DIST
        do_chroot $dir subscription-manager register --force --username=$RHN_USERNAME --password=$RHN_PASSWORD
        attach_pool_rh_cdn $dir $RHN_CDN_POOL_ID
        add_rh_cdn_repo $dir rhel-7-server-optional-rpms
        install_packages $dir make rubygems $RAKE
        remove_epel_repository $DIST
        unregister_cdn $dir
	;;
    "CentOS")
        case "$CODENAME_MAJOR" in
            6)
                RAKE=rake
                ;;
            7)
                RAKE=rubygem-rake
                ;;
        esac
        add_epel_repository $DIST
        install_packages $dir make rubygems $RAKE
        remove_epel_repository $DIST
	;;
    *)
        install_packages $dir rake make
        ;;
esac

# Pin the good dependencies for having rspec (< 3) & serverspec
do_chroot $dir gem install --no-ri --no-rdoc bundler
cp files/Gemfile-install-server $dir/tmp/Gemfile
do_chroot $dir bundle install --gemfile=/tmp/Gemfile


#####################
# OpenStack Clients #
#####################

# used by tempest and inception.sh

declare -A openstack_packages
openstack_packages=(
    ["deb"]="
        python-cinderclient \
        python-glanceclient \
        python-heatclient \
        python-ironicclient \
        python-keystoneclient \
        python-neutronclient \
        python-novaclient \
        python-saharaclient \
        python-swiftclient \
        python-ceilometerclient \
        python-troveclient \
        python-swiftclient \
        nova-common \
"

    ["rpm"]="
        python-cinderclient \
        python-glanceclient \
        python-heatclient \
        python-keystoneclient \
        python-neutronclient \
        python-novaclient \
        python-saharaclient \
        python-swiftclient \
        python-ceilometerclient \
        python-swiftclient \
        openstack-nova-common \
")

case "$OS" in
    "Debian"|"Ubuntu")
        update_repositories $dir
        ;;
    "CentOS")
        add_epel_repository $DIST
        install_packages $dir $(get_openstack_repository $DIST $dir $OS_VERS)
        ;;
    "RedHatEnterpriseServer")
        case "$CODENAME_MAJOR" in
            6)
              # Red Hat OpenStack 4.0 and 5b
              add_rhn_channel rhel-x86_64-server-6-ost-4
              add_rhn_channel rhel-x86_64-server-6-ost-beta
              ;;
            7)
              # Attach to the pool "Red Hat Enterprise Linux OpenStack Platform (Physical)"
              do_chroot $dir subscription-manager register --force --username=$RHN_USERNAME --password=$RHN_PASSWORD
              attach_pool_rh_cdn $dir $RHN_CDN_POOL_ID

              # Red Hat OpenStack 5
              add_rh_cdn_repo $dir rhel-7-server-openstack-5.0-rpms
              # python-subunit is on EPEL from rdo
              install_packages $dir $(get_openstack_repository centos $dir $OS_VERS)
              ;;
        esac
        ;;
esac

if [ $OS = "RedHatEnterpriseServer" ]; then
    add_epel_repository $DIST
fi

install_packages_disabled $dir ${openstack_packages[$(package_type)]}

case "$OS" in
    "RedHatEnterpriseServer"|"CentOS")
        install_packages $dir python-subunit python-devel libffi-devel
        ;;
    *)
        install_packages $dir python-dev libffi-dev subunit
        ;;
esac

remove_epel_repository $DIST

if [ $OS = CentOS ]; then
    remove_packages $dir $(basename $(get_openstack_repository $DIST $dir $OS_VERS) .noarch.rpm)
fi

if [ $OS = RedHatEnterpriseServer ]; then
  unregister_cdn $dir
fi

###########
# Jenkins #
###########

$SRC/jenkins.install $dir $dir $version

# Running jenkins + puppetdb on the same node:
# do not use the same port as the puppetdb
if [ -r $dir/etc/sysconfig/jenkins ]; then
    JENKINS_CFG=$dir/etc/sysconfig/jenkins
else
    JENKINS_CFG=$dir/etc/default/jenkins
fi
sed -i 's/HTTP_PORT=8080/HTTP_PORT=8282/' $JENKINS_CFG

#################
# Log Collector #
#################

if [ $OS = Debian ]; then
    $SRC/logcollector.install $dir $dir $version
else
  # TODO:
  echo "Log Collector can't be build now on Red Hat / CentOS"
fi

###########
# Tempest #
###########

$SRC/tempest.install $dir $dir $version

# install-server.install ends here
