#!/bin/bash
#
# Copyright (C) 2014 eNovance SAS <licensing@enovance.com>
#
# Author: Frederic Lepied <frederic.lepied@enovance.com>
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

src="$1"
dir="$2"
version="$3"
ROLE=install-server

ORIG=$(cd $(dirname $0); pwd)

. ${ORIG}/functions

if [ -z "$OS_VERS" ]; then
    echo "OS_VERS is not set, Icehouse will be built by default"
    OS_VERS=icehouse
fi

update_repositories $dir

###########
# eDeploy #
###########

$ORIG/deploy.install $dir $dir $version
install_packages_disabled $dir dnsmasq


###########
# Ansible #
###########

case "$OS" in
    "Debian")
        do_chroot $dir apt-key adv --keyserver keyserver.ubuntu.com --recv 049ED9B94765572E
        cat > ${dir}/etc/apt/sources.list.d/wheezy-backports.list <<EOF
deb http://ftp.de.debian.org/debian wheezy-backports main
EOF
	install_packages $dir python-pandas python-jinja2 python-paramiko python-libxml2 libmysqlclient-dev libxml2-dev libxslt-dev libpq-dev python-dev python-virtualenv libffi-dev subunit
	install_packages $dir -t wheezy-backports linux-headers-3.14-0.bpo.1-amd64 linux-image-3.14-0.bpo.1-amd64
	do_chroot $dir pip install ansible
	;;
    "Ubuntu")
	install_packages $dir python-pandas python-jinja2 python-paramiko build-essential python-dev
	do_chroot $dir pip install ansible
	;;
    "CentOS"|"RedHatEnterpriseServer")
	add_epel_repository $DIST
        # TODO: missing packages in epel7: python-subunit, ansible
        install_packages $dir python-devel libffi-devel
        do_chroot $dir pip install ansible
	remove_epel_repository $DIST
	;;
esac


#################
# Puppet master #
#################

$SRC/puppet-master.install $dir $dir $version

# Serverspec

install_packages $dir rake make

case "$OS" in
    "RedHatEnterpriseServer")
	add_epel_repository $DIST
	install_packages $dir rubygems
	remove_epel_repository $DIST
	;;
    "CentOS")
	install_packages $dir rubygems
	;;
esac

# Pin the good dependencies for having rspec (< 3) & serverspec
do_chroot $dir gem install --no-ri --no-rdoc bundler
cp files/Gemfile-install-server $dir/tmp/Gemfile
do_chroot $dir bundle install --gemfile=/tmp/Gemfile


#####################
# OpenStack Clients #
#####################

# used by tempest and inception.sh

declare -A openstack_packages
openstack_packages=(
    ["deb"]="
        python-cinderclient \
        python-glanceclient \
        python-heatclient \
        python-ironicclient \
        python-keystoneclient \
        python-neutronclient \
        python-novaclient \
        python-saharaclient \
        python-swiftclient \
        python-ceilometerclient \
        python-troveclient \
        python-swiftclient \
        nova-common \
"

    ["rpm"]="
        python-cinderclient \
        python-glanceclient \
        python-heatclient \
        python-ironicclient \
        python-keystoneclient \
        python-neutronclient \
        python-novaclient \
        python-saharaclient \
        python-swiftclient \
        python-ceilometerclient \
        python-troveclient \
        python-swiftclient \
        openstack-nova-common \
")

case "$OS" in
    "Debian"|"Ubuntu")
        update_repositories $dir
    ;;
    "CentOS")
        install_packages $dir $(get_openstack_repository $DIST $dir $OS_VERS)
        ;;&
    "RedHatEnterpriseServer")
        case "$CODENAME_MAJOR" in
            6)
              # Red Hat OpenStack 4.0 and 5b
              add_rhn_channel rhel-x86_64-server-6-ost-4
              add_rhn_channel rhel-x86_64-server-6-ost-beta
              ;;
            7)
              # Attach to the pool "Red Hat Enterprise Linux OpenStack Platform (Physical)"
              attach_pool_rh_cdn $dir $RHN_CDN_POOL_ID

              # Red Hat OpenStack 5
              add_rh_cdn_repo $dir rhel-7-server-openstack-5.0-rpms
              ;;
        esac
install_packages_disabled $dir ${openstack_packages[$(package_type)]}

if [ $OS = CentOS ]; then
    remove_packages $dir $(basename $(get_openstack_repository $DIST $dir $OS_VERS) .noarch.rpm)
fi

###########
# Jenkins #
###########

$SRC/jenkins.install $dir $dir $version

# Running jenkins + puppetdb on the same node:
# do not use the same port as the puppetdb
if [ -r $dir/etc/sysconfig/jenkins ]; then
    JENKINS_CFG=$dir/etc/sysconfig/jenkins
else
    JENKINS_CFG=$dir/etc/default/jenkins
fi
sed -i 's/HTTP_PORT=8080/HTTP_PORT=8282/' $JENKINS_CFG

#################
# Log Collector #
#################

if [ $OS = Debian ]; then
    $SRC/logcollector.install $dir $dir $version
else
  # TODO:
  echo "Log Collector can't be build now on Red Hat / CentOS"
fi

###########
# Tempest #
###########

$SRC/tempest.install $dir $dir $version

# install-server.install ends here
