#!/bin/bash
#
# Copyright (C) 2013-2014 eNovance SAS <licensing@enovance.com>
#
# Author: Emilien Macchi <emilien.macchi@enovance.com>
#         Gonéri Le Bouder <goneri.lebouder@enovance.com>
#         Nicolas Auvray <nicolas.auvray@enovance.com>
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

src="$1"
dir="$2"
version="$3"
ROLE=openstack-full

ORIG=$(cd $(dirname $0); pwd)

. ${ORIG}/functions
. ./repositories

case $version in
  *-I.*)
    OS_VERS=icehouse
    ;;
  *-J.*)
    OS_VERS=juno
    ;;
  *)
    echo "unsupported version $version" 1>&2
    exit 1
    ;;
esac

# Specify the ICE (Ceph for Enterprise) release
# 1.2 = firefly
ICE_RELEASE_KMOD=1.2
ICE_RELEASE=1.2.2

install_ib_if_needed $ORIG $dir

function build_dkms() {
    local package=$1
    local name=$2
    local kernel=$3

    local version=`do_chroot $dir dpkg-query -W -f='${Version}' "$package" \
        |rev|cut -d- -f2-|rev|cut -d':' -f2|tr -d "\n"`
    local isadded=`do_chroot $dir dkms status -m "$name" -v "$version"`

    if [ "x${isadded}" = "x" ] ; then
        do_chroot $dir dkms add -m "$name" -v "$version"
    fi

    unset ARCH
    do_chroot $dir dkms build -m "$name" -v "$version" -k "$kernel"
    do_chroot $dir dkms install -m "$name" -v "$version" -k "$kernel"
}

case "$OS" in
    "Debian")
     do_chroot $dir apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 0xcbcb082a1bb943db
     cat > ${dir}/etc/apt/sources.list.d/maria.list <<EOF
deb http://nwps.ws/pub/mariadb/repo/5.5/debian $DIST main
EOF
     do_chroot $dir apt-key adv --keyserver keyserver.ubuntu.com --recv 0x9ECBEC467F0CEB10
     cat > ${dir}/etc/apt/sources.list.d/mongodb.list <<EOF
deb http://downloads-distro.mongodb.org/repo/debian-sysvinit dist 10gen
EOF
     do_chroot $dir apt-key adv --keyserver keyserver.ubuntu.com --recv 0x7ebfdd5d17ed316d
     cat > ${dir}/etc/apt/sources.list.d/ceph.list <<EOF
deb http://eu.ceph.com/debian-firefly $DIST main
EOF
     cat > ${dir}/etc/apt/preferences.d/mariadb <<EOF
Package: *
Pin: release o=MariaDB,n=${DIST},l=MariaDB,c=main
Pin-Priority: 900
EOF
     add_rabbitmq_repo
    ;;
    "Ubuntu")
     do_chroot $dir apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 0xcbcb082a1bb943db
     cat > ${dir}/etc/apt/sources.list.d/maria.list <<EOF
deb http://nwps.ws/pub/mariadb/repo/5.5/ubuntu $DIST main
EOF
     do_chroot $dir apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10
     cat > ${dir}/etc/apt/sources.list.d/mongodb.list <<EOF
deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen
EOF
     do_chroot $dir apt-key adv --keyserver keyserver.ubuntu.com --recv 0x7ebfdd5d17ed316d
     cat > ${dir}/etc/apt/sources.list.d/ceph.list <<EOF
deb http://eu.ceph.com/debian-firefly $DIST main
EOF
     cat > ${dir}/etc/apt/preferences.d/mariadb <<EOF
Package: *
Pin: release o=MariaDB,n=${DIST},l=MariaDB,c=main
Pin-Priority: 900
EOF
     add_rabbitmq_repo
    ;;
    "CentOS"|"RedHatEnterpriseServer")
        # mongodb do not support systemd correctly so don't use it for EL7
        if [ "$CODENAME_MAJOR" == "6" ]; then
            cat > ${dir}/etc/yum.repos.d/mongodb.repo <<EOF
[mongodb]
name=MongoDB Repository
baseurl=http://downloads-distro.mongodb.org/repo/redhat/os/x86_64/
gpgcheck=0
enabled=1
EOF
            cat > ${dir}/etc/yum.repos.d/mariadb.repo <<EOF
# MariaDB 5.5 RedHat repository list - created 2013-12-17 16:18 UTC
# http://mariadb.org/mariadb/repositories/
[mariadb]
name = MariaDB
baseurl = http://yum.mariadb.org/5.5/rhel6-amd64
          http://os-ci-admin.ring.enovance.com/distrib/mariadb/rhel6-amd64
gpgkey=https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
gpgcheck=1
EOF
            cat >> ${dir}/etc/yum.repos.d/ceph.repo <<EOF
[ceph-extras]
name=Ceph Extras
baseurl=http://ceph.com/packages/ceph-extras/rpm/rhel6.5/x86_64/
enabled=1
priority=2
gpgcheck=1
type=rpm-md
gpgkey=https://ceph.com/git/?p=ceph.git;a=blob_plain;f=keys/release.asc

[ceph-qemu-source]
name=Ceph Extras Sources
baseurl=http://ceph.com/packages/ceph-extras/rpm/rhel6.5/SRPMS/
enabled=1
priority=2
gpgcheck=1
type=rpm-md
gpgkey=https://ceph.com/git/?p=ceph.git;a=blob_plain;f=keys/release.asc
EOF
        fi

        add_rabbitmq_repo
        ;;
    *)
        fatal_error "OS ($OS) or Release not supported"
        ;;
esac

declare -A os_packages
os_packages=(
    ["deb"]="\
        apache2 \
        build-essential \
        ceph \
        ceph-mds \
        ceilometer-agent-central \
        ceilometer-alarm-evaluator \
        ceilometer-alarm-notifier \
        ceilometer-api \
        ceilometer-collector \
        ceilometer-agent-notification \
        cinder-api \
        cinder-backup \
        cinder-scheduler \
        cinder-volume \
        euca2ools \
        galera \
        git \
        glance \
        haproxy \
        heat-api \
        heat-api-cfn \
        heat-api-cloudwatch \
        heat-engine \
        keepalived \
        keystone \
        libdbd-mysql-perl \
        libffi-dev \
        lsof \
        mariadb-client \
        mariadb-galera-server \
        memcached \
        mongodb-10gen \
        mysql-client \
        neutron-dhcp-agent \
        neutron-l3-agent \
        neutron-lbaas-agent \
        neutron-metadata-agent \
        neutron-metering-agent \
        neutron-plugin-linuxbridge-agent \
        neutron-plugin-openvswitch-agent \
        neutron-plugin-cisco \
        neutron-server \
        nfs-common \
        nova-api \
        nova-cert \
        nova-compute-kvm \
        nova-conductor \
        nova-consoleauth \
        nova-consoleproxy \
        nova-scheduler \
        openstack-compute-node \
        openstack-dashboard \
        openstack-dashboard-apache \
        openstack-pkg-tools \
        openvswitch-switch \
        pacemaker \
        pm-utils \
        python-argparse \
        python-dev \
        python-openstackclient \
        python-psutil \
        python-swiftclient \
        python-troveclient \
        python-trove \
        rabbitmq-server \
        ruby-activerecord \
        ruby-sqlite3 \
        screen \
        subunit \
        swift-account \
        swift-container \
        swift-object \
        swift-plugin-s3 \
        swift-proxy \
        sysfsutils \
        trove-api \
        trove-conductor \
        trove-guestagent \
        trove-taskmanager \
        unzip \
        xfsprogs \
        xinetd
"

    ["rpm"]="
        MySQL-python \
        corosync \
        galera \
        git \
        haproxy \
        httpd \
        mod_ssl \
        keepalived \
        libffi-devel \
        libreswan \
        lsof \
        memcached \
        nfs-utils \
        novnc \
        ntp \
        openstack-ceilometer-alarm \
        openstack-ceilometer-api \
        openstack-ceilometer-central \
        openstack-ceilometer-collector \
        openstack-ceilometer-compute \
        openstack-ceilometer-ipmi \
        openstack-ceilometer-notification \
        openstack-cinder \
        openstack-dashboard \
        openstack-glance \
        openstack-heat-api \
        openstack-heat-api-cfn \
        openstack-heat-api-cloudwatch \
        openstack-heat-engine \
        openstack-ironic-api \
        openstack-ironic-conductor \
        openstack-ironic-discoverd \
        openstack-keystone \
        openstack-neutron \
        openstack-neutron-cisco \
        openstack-neutron-linuxbridge \
        openstack-neutron-metering-agent \
        openstack-neutron-ml2 \
        openstack-neutron-openvswitch \
        openstack-neutron-sriov-nic-agent \
        openstack-neutron-vpn-agent \
        openstack-nova-api \
        openstack-nova-cells \
        openstack-nova-cert \
        openstack-nova-compute \
        openstack-nova-conductor \
        openstack-nova-console \
        openstack-nova-novncproxy \
        openstack-nova-serialproxy \
        openstack-nova-scheduler \
        openstack-sahara \
        openstack-selinux \
        openstack-swift-account \
        openstack-swift-container \
        openstack-swift-object \
        openstack-swift-proxy \
        openstack-trove-api \
        openstack-trove-common \
        openstack-trove-conductor \
        openstack-trove-guestagent \
        openstack-trove-taskmanager \
        openvswitch \
        pacemaker \
        pcs \
        python-cinderclient \
        python-devel \
        python-kombu \
        python-lesscpy \
        python-memcached \
        python-openstackclient \
        python-psutil \
        python-swiftclient \
        rabbitmq-server \
        redis \
        rubygem-json \
        rubygems \
        sysfsutils \
        xfsprogs \
        xinetd"
)

declare -A prod_packages
prod_packages=(
    ["deb"]="
        at \
        bash-completion \
        crash \
        dnsutils \
        file \
        iotop \
        less \
        ltrace \
        manpages \
        manpages-dev \
        mtr \
        ncdu \
        nmap \
        percona-toolkit \
        strace \
        sysstat \
        telnet \
        tmux \
        traceroute \
        w3m
"
    ["rpm"]="
        bash-completion \
        crash \
        iotop \
        ltrace \
        ipa-client \
        mtr \
        nmap \
        nmap-ncat \
        sos \
        strace \
        sysstat \
        telnet \
        tmux \
        traceroute \
        vim-enhanced
")

declare -A backup_packages
backup_packages=( 
    ["deb"]="
        xtrabackup
")

case "$OS" in
    "Debian")
        add_percona_deb_repo
        update_repositories $dir
        install_packages_disabled $dir -t wheezy-backports linux-headers-amd64 linux-image-amd64 redis-server
        install_packages_disabled $dir ${backup_packages[$(package_type)]}
        install_packages_disabled $dir ${prod_packages[$(package_type)]}
    ;&
    "Ubuntu")
        install_packages_disabled $dir ${os_packages[$(package_type)]}
        echo "" > $dir/etc/nova/nova-compute.conf
        # TODO(EmilienM) Dirty hack to fix spice and novnc
        do_chroot $dir chmod 777 /var/run/shm ; chmod +t /var/run/shm
        sed -i 's/NOVA_CONSOLE_PROXY_TYPE=spicehtml5/NOVA_CONSOLE_PROXY_TYPE=novnc/g' $dir/etc/default/nova-consoleproxy
    ;;
    "RedHatEnterpriseServer")
        case "$CODENAME_MAJOR" in
            6)
              # Red Hat OpenStack 4.0 and 5b
              add_rhn_channel rhel-x86_64-server-6-ost-4
              add_rhn_channel rhel-x86_64-server-6-ost-beta

              # xfsprogs is in Red Hat Common for RHEL Server (v. 6)
              add_rhn_channel rhel-x86_64-server-sfs-6

              # haproxy is in RHEL Server Load Balancer (v. 6 for 64-bit x86_64)
              add_rhn_channel rhel-x86_64-server-lb-6

              # pacemaker is in RHEL Server High Availability (v. 6 for 64-bit x86_64)
              add_rhn_channel rhel-x86_64-server-ha-6
              ;;
            7)
              # Attach to the pool "Red Hat Enterprise Linux OpenStack Platform (Physical)"
              attach_pool_rh_cdn $dir $RHN_CDN_POOL_ID

              # Red Hat OpenStack 6
              add_rh_cdn_repo $dir rhel-7-server-openstack-6.0-rpms

              # pacemaker is in RHEL Server High Availability (v.7 for 64-bit x86_64)
              add_rh_cdn_repo $dir rhel-ha-for-rhel-7-server-rpms

              # mongodb-server is in Red Hat Software Collections
              add_rh_cdn_repo $dir rhel-server-rhscl-7-rpms
              # install production packages
              install_packages_disabled $dir ${prod_packages[$(package_type)]}
              ;;
        esac

        # qemu-kvm-rhev provides a kvm that supersedes the standard qemu-kvm.
        # This package is not yet available in CentOS. So we have to take care
        # of that.
        install_packages $dir qemu-kvm-rhev qemu-img-rhev
        case "$CODENAME_MAJOR" in
            6)
              # Force to download qemu-kvm and qemu-img from ceph.com
              do_chroot $dir rpm -e qemu-kvm-rhev qemu-img-rhev --nodeps
              ceph_url="http://ceph.com/packages/ceph-extras/rpm/rhel6.5/x86_64"
              do_chroot $dir rpm -ivh $ceph_url/qemu-img-0.12.1.2-2.415.el6.3ceph.x86_64.rpm $ceph_url/qemu-kvm-0.12.1.2-2.415.el6.3ceph.x86_64.rpm
              ;;
        esac

        # Install ICE (Ceph for Enterprise) if possible, otherwise fall back to ceph.com
        # packages (community edition)
        if [ -z "$CEPH_USERNAME" ] || [ -z "$CEPH_PASSWORD" ]; then
            echo "CEPH_USERNAME or CEPH_PASSWORD are not set, we fall back to Ceph Community Edition."
            add_ceph_rpm_repo
            install_packages_disabled $dir ceph
        else
            # drop librados2 and librbd1 that will be re-installed from ICE
            remove_packages $dir librados2 librbd1
            ICE_URL=https://$CEPH_USERNAME:$CEPH_PASSWORD@download.inktank.com/enterprise
            KMOD_REL=3.10-0.1.20140702gitdc9ac62.el7.x86_64
            wget --no-verbose $ICE_URL/$ICE_RELEASE/ICE-$ICE_RELEASE-rhel7.tar.gz $ICE_URL/$ICE_RELEASE_KMOD/kmod-libceph-$KMOD_REL.rpm $ICE_URL/$ICE_RELEASE_KMOD/kmod-rbd-$KMOD_REL.rpm
            tar xzvf ICE-$ICE_RELEASE-rhel7.tar.gz
            do_chroot $dir mkdir /tmp/ice_pkg
            mv kmod*.rpm ceph/*/* $dir/tmp/ice_pkg
            cat > ${dir}/etc/yum.repos.d/ice.repo <<EOF
[ice]
name=Inktank Ceph Enterprise - local packages for Ceph
baseurl=file:///tmp/ice_pkg
enabled=1
gpgcheck=0
protect=1
priority=1
EOF
            update_system $dir
            install_packages_disabled $dir /tmp/ice_pkg/kmod-rbd-$KMOD_REL.rpm /tmp/ice_pkg/kmod-libceph-$KMOD_REL.rpm ceph
            rm $dir/etc/yum.repos.d/ice.repo
        fi
    ;;& # → means "continue"
    "CentOS")
        install_packages $dir $(get_openstack_repository $DIST $dir $OS_VERS)
        install_packages $dir qemu-kvm
        add_epel_repository $DIST
        install_packages_disabled $dir libunwind
        remove_epel_repository $DIST
        add_ceph_rpm_repo
        install_packages_disabled $dir ceph
    ;;&
    "CentOS"|"RedHatEnterpriseServer")
        if [ "$CODENAME_MAJOR" == "6" ]; then
            EXTRA_RPMS="fence-agents cman MariaDB-Galera-server mongodb-org mongodb-org-server"
        else
            EXTRA_RPMS="fence-agents-all mariadb-galera-server mariadb mongodb mongodb-server"
        fi

        if [ "$OS" == "RedHatEnterpriseServer" ]; then
            # Set priority to one for RH repos
            do_chroot $dir sed -i -e '/\[rhel-ha-for-rhel-7-server-rpms\]/a priority = 2' \
                                  -e '/\[rhel-server-rhscl-7-rpms\]/a priority = 2' \
                                  -e '/\[rhel-7-server-rpms = 2' /etc/yum.repos.d/redhat.repo
        fi

        add_epel_repository $DIST
        install_packages_disabled $dir ${os_packages[$(package_type)]} $EXTRA_RPMS

        if [ "$OS" == "RedHatEnterpriseServer" ]; then
            # TODO (spredzy) : The following line prevent RabbitMQ from
            # starting. A discussion is in progress with RH people to
            # find what is the cause
            do_chroot $dir sed -i 's/Requires=epmd@0.0.0.0.socket/#Requires=epmd@0.0.0.0.socket/g' /usr/lib/systemd/system/rabbitmq-server.service
        fi

        # TODO (spredzy): Install selinux policies
        # while the issues are fixed upstream
        do_chroot $dir mkdir -p /usr/share/selinux/custom
        cp $SRC/files/selinux/*.pp ${dir}/usr/share/selinux/custom

        # Drop me after https://bugs.launchpad.net/puppet-openstack-cloud/+bug/1410863
        sed -i "s/300/30/g" ${dir}/usr/lib/systemd/system/mariadb.service

        remove_epel_repository $DIST
    ;;
    *)
    fatal_error "OS or Release not supported"
    ;;
esac

$SRC/logcollector.install $dir $dir $version
$SRC/monitor-server.install $dir $dir $version

# TODO (spredzy): https://bugzilla.redhat.com/show_bug.cgi?id=1159894
install_monitoring

# add galera-status script to validate MySQL Galera cluster sanity
cp $SRC/files/galera-status $dir/usr/sbin

clear_packages_cache $dir
cp $SRC/files/disable-tso $dir/etc/init.d/

# openstack-full.install ends here
