#!/bin/bash
#
# Copyright (C) 2013-2014 eNovance SAS <licensing@enovance.com>
#
# Author: Emilien Macchi <emilien.macchi@enovance.com>
#         Gonéri Le Bouder <goneri.lebouder@enovance.com>
#         Nicolas Auvray <nicolas.auvray@enovance.com>
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

src="$1"
dir="$2"
version="$3"
ROLE=openstack-full

ORIG=$(cd $(dirname $0); pwd)

. ${ORIG}/functions
. ./repositories

if [ -z "$OS_VERS" ]; then
    echo "OS_VERS is not set, Icehouse will be built by default"
    OS_VERS=icehouse
fi

install_ib_if_needed $ORIG $dir

function build_dkms() {
    local package=$1
    local name=$2
    local kernel=$3

    local version=`do_chroot $dir dpkg-query -W -f='${Version}' "$package" \
        |rev|cut -d- -f2-|rev|cut -d':' -f2|tr -d "\n"`
    local isadded=`do_chroot $dir dkms status -m "$name" -v "$version"`

    if [ "x${isadded}" = "x" ] ; then
        do_chroot $dir dkms add -m "$name" -v "$version"
    fi

    unset ARCH
    do_chroot $dir dkms build -m "$name" -v "$version" -k "$kernel"
    do_chroot $dir dkms install -m "$name" -v "$version" -k "$kernel"
}

function add_rabbitmq_deb_repo() {
    do_chroot $dir wget -O- ${RABBITMQ_URL:=http://www.rabbitmq.com/}rabbitmq-signing-key-public.asc | do_chroot $dir apt-key add -
    cat > ${dir}/etc/apt/sources.list.d/rabbitmq.list <<EOF
deb ${RABBITMQ_URL:=http://www.rabbitmq.com/}debian/ testing main
EOF
}

function add_percona_deb_repo() {
    do_chroot ${dir} apt-key adv --keyserver keys.gnupg.net --recv-keys 1C4CBDCDCD2EFD2A
    cat > ${dir}/etc/apt/sources.list.d/percona.list <<EOF
deb http://repo.percona.com/apt wheezy main
EOF
    cat > ${dir}/etc/apt/preferences.d/percona-pin.pref << EOF
Explanation: : percona-pin
Package: *
Pin: origin "repo.percona.com"
Pin-Priority: 100
EOF
}

case "$OS" in
    "Debian")
     do_chroot $dir apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 0xcbcb082a1bb943db
     cat > ${dir}/etc/apt/sources.list.d/maria.list <<EOF
deb http://ftp.igh.cnrs.fr/pub/mariadb/repo/5.5/debian $DIST main
EOF
     do_chroot $dir apt-key adv --keyserver keyserver.ubuntu.com --recv 0x9ECBEC467F0CEB10
     cat > ${dir}/etc/apt/sources.list.d/mongodb.list <<EOF
deb http://downloads-distro.mongodb.org/repo/debian-sysvinit dist 10gen
EOF
     do_chroot $dir apt-key adv --keyserver keyserver.ubuntu.com --recv 0x7ebfdd5d17ed316d
     cat > ${dir}/etc/apt/sources.list.d/ceph.list <<EOF
deb http://eu.ceph.com/debian-firefly $DIST main
EOF
     do_chroot $dir apt-key adv --keyserver keyserver.ubuntu.com --recv 049ED9B94765572E
     cat > ${dir}/etc/apt/sources.list.d/qemu-backports.list <<EOF
deb http://ftp.de.debian.org/debian wheezy-backports main
EOF
     do_chroot $dir apt-key adv --keyserver keyserver.ubuntu.com --recv 049ED9B94765572E
     cat > ${dir}/etc/apt/sources.list.d/haproxy-wheezy.list <<EOF
deb http://41.apt-proxy.gplhost.com/debian haproxy-wheezy main
EOF
     do_chroot ${dir} wget -O- http://41.apt-proxy.gplhost.com/debian/repository_key.asc | do_chroot $dir apt-key add -
     cat > ${dir}/etc/apt/preferences.d/haproxy <<EOF
Package: *
Pin: release a=stable,n=haproxy-wheezy,c=main
Pin: origin 41.apt-proxy.gplhost.com
Pin-Priority: 1002
EOF
     cat > ${dir}/etc/apt/preferences.d/mariadb <<EOF
Package: *
Pin: origin ftp.igh.cnrs.fr
Pin-Priority: 900
EOF
     add_rabbitmq_deb_repo
     add_percona_deb_repo
    ;;
    "Ubuntu")
     do_chroot $dir apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 0xcbcb082a1bb943db
     cat > ${dir}/etc/apt/sources.list.d/maria.list <<EOF
deb [trusted=yes] http://ftp.igh.cnrs.fr/pub/mariadb/repo/5.5/ubuntu $DIST main
EOF
     do_chroot $dir apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10
     cat > ${dir}/etc/apt/sources.list.d/mongodb.list <<EOF
deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen
EOF
     do_chroot $dir apt-key adv --keyserver keyserver.ubuntu.com --recv 0x7ebfdd5d17ed316d
     cat > ${dir}/etc/apt/sources.list.d/ceph.list <<EOF
deb http://eu.ceph.com/debian-firefly $DIST main
EOF
     add_rabbitmq_deb_repo
     add_percona_deb_repo
    ;;
    "CentOS"|"RedHatEnterpriseServer")
        cat > ${dir}/etc/yum.repos.d/mariadb.repo <<EOF
# MariaDB 5.5 RedHat repository list - created 2013-12-17 16:18 UTC
# http://mariadb.org/mariadb/repositories/
[mariadb]
name = MariaDB
baseurl = http://yum.mariadb.org/5.5/rhel6-amd64
          http://os-ci-admin.ring.enovance.com/distrib/mariadb/rhel6-amd64
gpgkey=https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
gpgcheck=1
EOF
        cat > ${dir}/etc/yum.repos.d/mongodb.repo <<EOF
[mongodb]
name=MongoDB Repository
baseurl=http://downloads-distro.mongodb.org/repo/redhat/os/x86_64/
gpgcheck=0
enabled=1
EOF
        cat > ${dir}/etc/yum.repos.d/ceph.repo <<EOF
[ceph-noarch]
name=Ceph packages for $basearch
baseurl=http://ceph.com/rpm/rhel$CODENAME_MAJOR/noarch/
enabled=1
gpgcheck=1
type=rpm-md
gpgkey=https://ceph.com/git/?p=ceph.git;a=blob_plain;f=keys/release.asc

[ceph]
name=Ceph packages for $basearch
baseurl=http://ceph.com/rpm/rhel$CODENAME_MAJOR/x86_64/
enabled=1
gpgcheck=1
type=rpm-md
gpgkey=https://ceph.com/git/?p=ceph.git;a=blob_plain;f=keys/release.asc
EOF
        if [ "$CODENAME_MAJOR" == "6" ]; then
            cat > ${dir}/etc/yum.repos.d/mariadb.repo <<EOF
# MariaDB 5.5 RedHat repository list - created 2013-12-17 16:18 UTC
# http://mariadb.org/mariadb/repositories/
[mariadb]
name = MariaDB
baseurl = http://yum.mariadb.org/5.5/rhel6-amd64
          http://os-ci-admin.ring.enovance.com/distrib/mariadb/rhel6-amd64
gpgkey=https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
gpgcheck=1
EOF
            cat >> ${dir}/etc/yum.repos.d/ceph.repo <<EOF

[ceph-extras]
name=Ceph Extras
baseurl=http://ceph.com/packages/ceph-extras/rpm/rhel6.5/x86_64/
enabled=1
priority=2
gpgcheck=1
type=rpm-md
gpgkey=https://ceph.com/git/?p=ceph.git;a=blob_plain;f=keys/release.asc

[ceph-qemu-source]
name=Ceph Extras Sources
baseurl=http://ceph.com/packages/ceph-extras/rpm/rhel6.5/SRPMS/
enabled=1
priority=2
gpgcheck=1
type=rpm-md
gpgkey=https://ceph.com/git/?p=ceph.git;a=blob_plain;f=keys/release.asc
EOF
        fi
        ;;
    *)
        fatal_error "OS ($OS) or Release not supported"
        ;;
esac

declare -A os_packages
os_packages=(
    ["deb"]="\
        apache2 \
        build-essential \
        ceilometer-agent-central \
        ceilometer-alarm-evaluator \
        ceilometer-alarm-notifier \
        ceilometer-api \
        ceilometer-collector \
        ceilometer-agent-notification \
        ceph \
        ceph-mds \
        cinder-api \
        cinder-backup \
        cinder-scheduler \
        cinder-volume \
        euca2ools \
        galera \
        git \
        glance \
        haproxy \
        heat-api \
        heat-api-cfn \
        heat-api-cloudwatch \
        heat-engine \
        keepalived \
        keystone \
        libdbd-mysql-perl \
        libffi-dev \
        lsof \
        mariadb-client \
        mariadb-galera-server \
        memcached \
        mongodb-10gen \
        mysql-client \
        neutron-dhcp-agent \
        neutron-l3-agent \
        neutron-lbaas-agent \
        neutron-metadata-agent \
        neutron-metering-agent \
        neutron-plugin-linuxbridge-agent \
        neutron-plugin-openvswitch-agent \
        neutron-server \
        nfs-common \
        nova-api \
        nova-cert \
        nova-compute-kvm \
        nova-conductor \
        nova-consoleauth \
        nova-consoleproxy \
        nova-scheduler \
        openstack-compute-node \
        openstack-dashboard \
        openstack-dashboard-apache \
        openstack-pkg-tools \
        openvswitch-switch
        pacemaker \
        pm-utils \
        python-argparse \
        python-dev \
        python-swiftclient \
        python-troveclient \
        python-trove \
        rabbitmq-server \
        ruby-activerecord \
        ruby-sqlite3 \
        screen \
        subunit \
        swift-account \
        swift-container \
        swift-object \
        swift-plugin-s3 \
        swift-proxy \
        sysfsutils \
        trove-api \
        trove-conductor \
        trove-guestagent \
        trove-taskmanager \
        unzip \
        xfsprogs \
        xinetd
"

    ["rpm"]="
        MariaDB-Galera-server \
        MariaDB-client \
        MySQL-python \
        ceph \
        corosync \
        galera \
        git \
        haproxy \
        httpd \
        keepalived \
        libffi-devel \
        lsof \
        memcached \
        mongodb-org \
        mongodb-org-server \
        nfs-utils \
        novnc \
        ntp \
        openstack-ceilometer-alarm \
        openstack-ceilometer-api \
        openstack-ceilometer-central \
        openstack-ceilometer-collector \
        openstack-ceilometer-compute \
        openstack-ceilometer-notification \
        openstack-cinder \
        openstack-dashboard \
        openstack-glance \
        openstack-heat-api \
        openstack-heat-api-cfn \
        openstack-heat-api-cloudwatch \
        openstack-heat-engine \
        openstack-keystone \
        openstack-neutron \
        openstack-neutron-linuxbridge \
        openstack-neutron-metering-agent \
        openstack-neutron-ml2 \
        openstack-neutron-openvswitch \
        openstack-neutron-vpn-agent \
        openstack-nova-api \
        openstack-nova-cert \
        openstack-nova-compute \
        openstack-nova-conductor \
        openstack-nova-console \
        openstack-nova-novncproxy \
        openstack-nova-scheduler \
        openstack-swift-account \
        openstack-swift-container \
        openstack-swift-object \
        openstack-swift-proxy \
        openstack-trove \
        openvswitch-controller \
        pacemaker \
        pcs \
        python-cinderclient \
        python-devel \
        python-kombu \
        python-lesscpy \
        python-memcached \
        python-pip \
        python-swiftclient \
        python-trove \
        python-troveclient \
        rabbitmq-server \
        rubygem-json \
        rubygems \
        sysfsutils \
        xfsprogs \
        xinetd"
)

declare -A prod_packages
prod_packages=(
    ["deb"]="
        at \
        bash-completion \
        crash \
        dnsutils \
        file \
        iotop \
        less \
        ltrace \
        manpages \
        manpages-dev \
        mtr \
        ncdu \
        nmap \
        percona-toolkit \
        strace \
        sysstat \
        telnet \
        tmux \
        traceroute \
        w3m"
)

declare -A monitoring_packages
monitoring_packages=( 
    ["deb"]="
        bc \
        libjson-perl \
        libnagios-plugin-perl \
        nagios-plugin-check-multi \
        nagios-plugins-basic \
        nagios-plugins-standard \
        percona-nagios-plugins
"

    ["rpm"]="
        bc \
        nagios-plugins-all
")

declare -A backup_packages
backup_packages=( 
    ["deb"]="
        xtrabackup
")

declare -A logging_packages
logging_packages=( 
    ["deb"]="
        td-agent
"
    ["rpm"]="
        td-agent
")

add_fluentd_repo
update_repositories $dir

cd $dir/tmp
git clone https://github.com/enovance/openstack-monitoring.git

case "$OS" in
    "Debian")
        update_repositories $dir
        install_packages_disabled $dir -t wheezy-backports linux-headers-3.14-0.bpo.1-amd64 linux-image-3.14-0.bpo.1-amd64
        install_packages_disabled $dir ${backup_packages[$(package_type)]}
        install_packages_disabled $dir ${logging_packages[$(package_type)]}
        install_packages_disabled $dir ${prod_packages[$(package_type)]}
    ;&
    "Ubuntu")
        install_packages_disabled $dir ${os_packages[$(package_type)]}
        install_packages_disabled $dir ${monitoring_packages[$(package_type)]}
        cp -pv openstack-monitoring/scripts/*/* $dir/usr/lib/nagios/plugins
        echo "" > $dir/etc/nova/nova-compute.conf
    ;;
    "RedHatEnterpriseServer")
        # Red Hat OpenStack 4.0 and 5b
        add_rhn_channel rhel-x86_64-server-6-ost-4
        add_rhn_channel rhel-x86_64-server-6-ost-beta

        # xfsprogs is in Red Hat Common for RHEL Server (v. 6)
        add_rhn_channel rhel-x86_64-server-sfs-6

        # haproxy is in RHEL Server Load Balancer (v. 6 for 64-bit x86_64)
        add_rhn_channel rhel-x86_64-server-lb-6

        # pacemaker is in RHEL Server High Availability (v. 6 for 64-bit x86_64)
        add_rhn_channel rhel-x86_64-server-ha-6

        # qemu-kvm-rhev provides a kvm that supersedes the standard qemu-kvm.
        # This package is not yet available in CentOS. So we have to take care
        # of that.
        install_packages $dir qemu-kvm-rhev qemu-img-rhev


        # Force to download qemu-kvm and qemu-img from ceph.com
        do_chroot $dir rpm -e qemu-kvm-rhev qemu-img-rhev --nodeps
        ceph_url="http://ceph.com/packages/ceph-extras/rpm/rhel6.5/x86_64"
        do_chroot $dir rpm -ivh $ceph_url/qemu-img-0.12.1.2-2.415.el6.3ceph.x86_64.rpm $ceph_url/qemu-kvm-0.12.1.2-2.415.el6.3ceph.x86_64.rpm

    ;;& # → means "continue"
    "CentOS")
        install_packages $dir qemu-kvm
    ;;&
    "CentOS"|"RedHatEnterpriseServer")

        # We want to use rabbitmq on Redhat instead of QPID
        add_epel_repository $DIST

        if [ "$CODENAME_MAJOR" == "6" ]; then
            install_packages_disabled $dir ${logging_packages[$(package_type)]}
            EXTRA_RPMS="fence-agents cman spice-html5 python-subunit"
        else
            EXTRA_RPMS=fence-agents-all
        fi
        install_packages_disabled $dir ${os_packages[$(package_type)]} $EXTRA_RPMS
        install_packages_disabled $dir ${monitoring_packages[$(package_type)]}
        remove_epel_repository $DIST

        # python-kombu is outdated for now in Red Hat.
        # while they updating it, we use pip to install the last one required by OpenStack
        do_chroot $dir pip install --upgrade kombu
 
        do_chroot $dir chkconfig puppet on

        do_chroot $dir rpm -qv ${os_packages[$(package_type)]} || fatal_error "Some packages are not installed"

        cp -pv openstack-monitoring/scripts/*/* $dir/usr/lib64/nagios/plugins
    ;;
    *)
    fatal_error "OS or Release not supported"
    ;;
esac

# add galera-status script to validate MySQL Galera cluster sanity
cp $SRC/files/galera-status $dir/usr/sbin

clear_packages_cache $dir
rm -rf $dir/tmp/openstack-monitoring

# openstack-full.install ends here
