#!/bin/sh
#
# Copyright (C) 2014 eNovance SAS <licensing@enovance.com>
#
# Author: Frederic Lepied <frederic.lepied@enovance.com>
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

ROLE=$1
DVER=$2
FROM=$3
TO=$4
DEST=$5

set -e

mkdir -p ${DEST}/${DVER}-${TO}

./upgrade-from.d/${ROLE}_${FROM}_${TO}.upgrade ${DEST}/${DVER}-${FROM}/${ROLE} ${DEST}/${DVER}-${TO}/${ROLE} ${DVER}-${TO}
touch ${DEST}/${DVER}-${TO}/${ROLE}-${DVER}-${TO}

# upgrade-from ends here
