#!/bin/bash
### BEGIN INIT INFO
# Provides:          disable-tso
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: TSO disable script
# Description:       Disable TSO on Neutron interfaces
### END INIT INFO

# Authors: Emilien Macchi <emilien.macchi@enovance.com>
#          Sylvain Afchain <sylvain.afchain@enovance.com>
#          Dimitri Savineau <dimitri.savineau@enovance.com>

vm_netlink() {
  ethtool --offload $1 tso off gso off tx off ufo off gro off
}

router_netlink() {
  ip netns | grep qrouter | while read NS; do
    ip netns exec $NS ethtool --offload $1 tso off gso off tx off ufo off gro off
  done
}

ip_monitor() {
  ip monitor link | while read LINE; do
    IF=$(echo $LINE | egrep "^[0-9]" | cut -d ':' -f 2)
    case $IF in
      *qvo*|*qvb*|*qbr*)
        vm_netlink $IF
        ;;
       *qr*)
        router_netlink $IF
        ;;
    esac
  done
}	

case "$1" in
start)
        if [ -f /var/run/disable-tso.pid ]; then
          echo "TSO script is already running or lock file has not been deleted."
          exit 1
        else
          # These interfaces survive to reboot, so we need to ensure that TSO is disabled after reboot.
          ip link | awk -F ': ' '/qvb|qvo|qbr/{system("ethtool --offload "$2 " tso off gso off tx off ufo off gro off")}'
          # This command manages the TSO disabling on the fly.
          # For router netlinks, we don't need to run `ip link` at boot because namespaces don't survive to reboot.
          ip_monitor &
          touch /var/run/disable-tso.pid
          echo "Disabling TSO/GSO/GRO/UFO on QVB/QVO/QBR interfaces"
        fi
;;
stop)
        echo "Enabling TSO/GSO/GRO/UFO on QVB/QVO/QBR interfaces"
        if [ -f /var/run/disable-tso.pid ]; then
          pkill -xf '/sbin/ip monitor link'>&2
          rm /var/run/disable-tso.pid
        else
          echo "TSO script was not running or PID file is missing."
          exit 1
        fi
;;
*)
        echo "Usage: /etc/init.d/disable-tso {start|stop}"
        exit 1
;;
esac

exit 0
