#!/bin/sh
### BEGIN INIT INFO
# Provides:          disable-tso
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: TSO disable script
# Description:       Disable TSO on Neutron interfaces
### END INIT INFO

# Authors: Emilien Macchi <emilien.macchi@enovance.com>
#          Sylvain Afchain <sylvain.afchain@enovance.com>

case "$1" in
start)
        if [ -f /tmp/disable-tso-lock ]; then
          /sbin/ip monitor link | awk -F ': ' '/qvb|qvo|qbr/{system("ethtool --offload "$2 " tso off gso off tx off ufo off gro off")}'&
          /bin/touch /tmp/disable-tso-lock
          echo "Disabling TSO/GSO/GRO/UFO on QVB/QVO/QBR interfaces"
        else
          "TSO script is already running or lock file has not been deleted."
          exit 1
        fi
;;
stop)
        echo "Enabling TSO/GSO/GRO/UFO on QVB/QVO/QBR interfaces"
        if ps -e | grep '/sbin/ip monitor link'; then
          /usr/bin/pkill -xf '/sbin/ip monitor link'>&2
          /bin/rm /tmp/disable-tso-lock
        else
          "TSO script was not running."
          exit 1
        fi
;;
*)
        echo "Usage: /etc/init.d/disable-tso {start|stop}"
        exit 1
;;
esac

exit 0
